My memes page
Meme-of-the-Day/meme-of-the-day-filecoin pull request #20
Opened 2020-11-04 15:40 UTC by shad-k

2020-11-05 17:13 UTC, matprime approved these changes

2020-11-05 20:03 UTC, sylar217 requested changes

2020-11-05 20:03 UTC, sylar217 commented on src/pages/Upload.tsx
> +      const accounts = await web3.eth.requestAccounts();
This should be done only once in user flow and shared across the app states. This I believe would ask user to select the address once in upload page and once in my memes page.

2020-11-06 01:58 UTC, shad-k commented on src/pages/Upload.tsx
> +      const accounts = await web3.eth.requestAccounts();
If the user has already accepted on Upload page or the user has already uploaded in the past then it'll not ask again. The method either returns account or waits for user to accept.

2020-11-07 04:55 UTC, sylar217 approved these changes

2020-11-07 09:45 UTC, merged